name: Scrape Table Sums

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Playwright
        run: npm install playwright
      - name: Install Playwright Browsers
        run: npx playwright install
      - name: Scrape Tables (22f3000891@ds.study.iitm.ac.in)
        run: node scrape_tables.mjs
